language: node_js
node_js:
  - "0.10"
  - "0.11"
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@2.11.x && cat coverage/lcov.info | coveralls"
notifications:
  irc:
    channels: 
      - "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
